### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by mdings** [mmckegg/soundbank-sample#1]
I tried cloning the repo and running npm. It returns a general error. Also tried manually running the example but there is no sound output

**Comment by mmckegg** [comment]
Looks like this module might be broken now, sorry about that. You are welcome to try fixing it and **I will accept a pull request**, but I no longer use this module so won't be fixing it myself. 

You can try [audio-slot](https://github.com/mmckegg/audio-slot) instead, which is the spiritual successor to the `soundbank-*` modules.

**Comment by mdings** [comment]
Guess I'll be looking into audio-slot then. Closing this one.
